version = 0.1

[default.deploy.parameters]
stack_name = "golf-tourney-test-2"
resolve_s3 = true
s3_prefix = "golf-tourney-test-2"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "AdminKey=\"ADMIN_RTR\" EventsBucketName=\"golf-events\" StateBucketName=\"golf-state\" PublicBucketName=\"golf-public\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
